<a href="https://colab.research.google.com/github/SaBuMa/Inteligencia-Artificial/blob/main/Fisher_NaiveBayes%26DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias / Dataset / Preprocesamiento

In [1]:
# Importar Librerias a usar
import numpy as np # Para multiplicaciÓn entre matrices
from sklearn import datasets # Para importar el dataset de Fisher/Iris
from sklearn import metrics # Para importar las metricas como el Accuracy MCC y F1
from sklearn.preprocessing import StandardScaler # Para la seccion de preprocesamiento
from sklearn.model_selection import train_test_split # Para distribuir los datos del dataset en datos de entrenamiento y datos de prueba

from sklearn.metrics import matthews_corrcoef # Para el Coeficiente de relacion de Matthews
from sklearn.metrics import f1_score # Para el F-score balanceado o F-medida
from sklearn.metrics import accuracy_score # Para el Accuracy 

from sklearn.naive_bayes import MultinomialNB # Para el algoritmo de Naive Bayes Multinomial
from sklearn.tree import DecisionTreeClassifier # Para el algoritmo de Árboles de decisión

In [2]:
# Cargar los datos y preprocesarlos
iris = datasets.load_iris() # Se importa la libreria de Fisher/Iris
x = iris.data # Se asignan las caracteristicas a la variable x
y = iris.target # Se asignan las etiquetas a la variable y
# Se imprimen las variables creadas para el dataset para comprobar los datos 
#print(iris)
print(x[:5,])
print(y)
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.4, random_state=10) # Se Realiza la distribucion de datos entre entrenamiento y prueba

#scaler = StandardScaler() # Se usa el preprocesamiento para quitar la media y escalar los datos a una varianza unitaria
#scaler.fit(x_train) # El fit se realiza para los datos de entrenamiento 
# Se transforman los datos centrandolos en cero y escalandolos, para luego ser usados
#x_train = scaler.transform(x_train) 
#x_test = scaler.transform(x_test)

print(x.shape)
print(y.shape)
print(x_train.shape)
print(x_train[:5,])
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150, 4)
(150,)
(90, 4)
[[4.7 3.2 1.6 0.2]
 [4.6 3.1 1.5 0.2]
 [4.9 2.5 4.5 1.7]
 [5.1 2.5 3.  1.1]
 [6.7 3.1 5.6 2.4]]
(60, 4)
(90,)
(60,)


# Niave Bayes

In [3]:
# Uso del clasificador Naive Bayes Multinomial
NBrange = np.arange(1.0,10.0,0.5) # se crea un arreglo de valores para variar el hiperparametro alpha en NBmultinomial, Valores de alpha>0
#print(NBrange)
# Se crea una lista para la mas metricas
ACC=[]
MCC=[]
F1_micro=[]
F1_macro=[]
# Se crea el loop para variar el hiperparametro
for k in NBrange:
    #MultinomialNB()
    clf_NB = MultinomialNB(alpha=k, fit_prior=True, class_prior=None) # El parametro a iterar es el alpha para adición suavizada de (laplace/lidstone)

    clf_NB = clf_NB.fit(x_train, y_train) # Para cuando no se escalizan los datos
    #clf_NB = clf_NB.fit(x, y) # Para cuando se Escalizan los datos

    #print("Clasificación",clf.predict(x_train))
    #print("Probabilidad test vector",clf.predict_proba(x))
    #print("Mean Accuraccy= ",clf.score(x_train,y_train))

    y_NBpredicted = clf_NB.predict(x_train)
    # Aconinuación, se realiza el calculo de las metricas
    print("Iteracion=", k)
    #Accuracy
    ACC.append(clf_NB.score(x_train, y_train))
    print("Accuracy= ",ACC)
    #MCC 
    MCC.append(matthews_corrcoef(y_train,y_NBpredicted))
    print("Matthews= ",MCC)
    #F1 
    F1_micro.append(f1_score(y_train,y_NBpredicted,average='micro'))
    print("F1_micro= ",F1_micro)
    #F1 
    F1_macro.append(f1_score(y_train,y_NBpredicted,average='macro'))
    print("F1_macro= ",F1_macro, "\n")

Iteracion= 1.0
Accuracy=  [0.7111111111111111]
Matthews=  [0.6447017869439094]
F1_micro=  [0.7111111111111111]
F1_macro=  [0.5703703703703704] 

Iteracion= 1.5
Accuracy=  [0.7111111111111111, 0.7111111111111111]
Matthews=  [0.6447017869439094, 0.6447017869439094]
F1_micro=  [0.7111111111111111, 0.7111111111111111]
F1_macro=  [0.5703703703703704, 0.5703703703703704] 

Iteracion= 2.0
Accuracy=  [0.7111111111111111, 0.7111111111111111, 0.7111111111111111]
Matthews=  [0.6447017869439094, 0.6447017869439094, 0.6447017869439094]
F1_micro=  [0.7111111111111111, 0.7111111111111111, 0.7111111111111111]
F1_macro=  [0.5703703703703704, 0.5703703703703704, 0.5703703703703704] 

Iteracion= 2.5
Accuracy=  [0.7111111111111111, 0.7111111111111111, 0.7111111111111111, 0.7111111111111111]
Matthews=  [0.6447017869439094, 0.6447017869439094, 0.6447017869439094, 0.6447017869439094]
F1_micro=  [0.7111111111111111, 0.7111111111111111, 0.7111111111111111, 0.7111111111111111]
F1_macro=  [0.5703703703703704, 0.

#Decision Tree

In [6]:
# Uso del clasificador Arboles de decisión
DTrange = np.arange(0.0,0.3,0.01) # se crea un arreglo de valores para variar el hiperparametro ccp_alpha en Decision Tree, Valores de alpha>0
#print(DTrange)
# Se crea una lista para la mas metricas
ACC=[]
MCC=[]
F1_micro=[]
F1_macro=[]

# Se crea el loop para variar el hiperparametro
for k in DTrange:
  clf_DT = DecisionTreeClassifier(criterion="gini",splitter="best",random_state=0,max_features="log2",ccp_alpha=k) # Parametro a iterar ccp_alpha 
  clf_DT = clf_DT.fit(x_train, y_train)
  
  #print("Clasificación",clf.predict(x_train))
  #print("Probabilidad test vector",clf.predict_proba(x))
  #print("Mean Accuraccy= ",clf.score(x_train,y_train))

  y_DTpredicted = clf_DT.predict(x_train)

  # Aconinuación, se realiza el calculo de las metricas
  print("Valor de ccp_alpha=",k)
  #Accuracy
  ACC.append(clf_DT.score(x_train, y_train))
  print("Accuracy= ",ACC)
  #MCC 
  MCC.append(matthews_corrcoef(y_train,y_DTpredicted))
  print("Matthews= ",MCC)
  #F1_micro
  F1_micro.append(f1_score(y_train,y_DTpredicted,average='micro'))
  print("F1_micro= ",F1_micro)
  #F1_macro
  F1_macro.append(f1_score(y_train,y_DTpredicted,average='macro'))
  print("F1_macro= ",F1_macro, "\n")

Valor de ccp_alpha= 0.0
Accuracy=  [1.0]
Matthews=  [1.0]
F1_micro=  [1.0]
F1_macro=  [1.0] 

Valor de ccp_alpha= 0.01
Accuracy=  [1.0, 0.9888888888888889]
Matthews=  [1.0, 0.9834607479220027]
F1_micro=  [1.0, 0.9888888888888889]
F1_macro=  [1.0, 0.988419686532894] 

Valor de ccp_alpha= 0.02
Accuracy=  [1.0, 0.9888888888888889, 0.9888888888888889]
Matthews=  [1.0, 0.9834607479220027, 0.9834607479220027]
F1_micro=  [1.0, 0.9888888888888889, 0.9888888888888889]
F1_macro=  [1.0, 0.988419686532894, 0.988419686532894] 

Valor de ccp_alpha= 0.03
Accuracy=  [1.0, 0.9888888888888889, 0.9888888888888889, 0.9555555555555556]
Matthews=  [1.0, 0.9834607479220027, 0.9834607479220027, 0.9361080170496191]
F1_micro=  [1.0, 0.9888888888888889, 0.9888888888888889, 0.9555555555555556]
F1_macro=  [1.0, 0.988419686532894, 0.988419686532894, 0.953968253968254] 

Valor de ccp_alpha= 0.04
Accuracy=  [1.0, 0.9888888888888889, 0.9888888888888889, 0.9555555555555556, 0.9555555555555556]
Matthews=  [1.0, 0.983460